/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw3_template;
import java.io.FileReader;
import java.io.BufferedReader;

public class hw3 {
    public static void main(String[] args) {
        GraphArgParser parser = new GraphArgParser(args);
        String s = parser.getS();
        String t = parser.getT();
        String alg = parser.getAlg();


        // This should probably be part of the graph class that you write!
        BufferedReader is = null;
        try {
            is = new BufferedReader(new FileReader(parser.getGraphFile()));
            String line;
            while((line = is.readLine()) != null) {
                int c = Integer.parseInt(line.substring(4));
                System.out.printf("Edge (%c, %c) with weight %d\n", 
                    line.charAt(0), 
                    line.charAt(2), 
                    c);
            }
            is.close();
        } catch(Exception e) {
            System.err.println("File Error:");
            System.err.println(e);
            return;
        }


        System.out.println(alg);
        System.out.printf("Source: %s\n", s);
        System.out.printf("Target: %s\n", t);

    }
}
