/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pa2_template;
import java.io.FileReader;
import java.io.BufferedReader;

public class pa2 {
    public static void main(String[] args) {
        GraphArgParser parser = new GraphArgParser(args);

        // This should probably be part of the graph class that you write!
        BufferedReader is = null;
        try {
            is = new BufferedReader(new FileReader(parser.getGraphFile()));
            String line;
            while((line = is.readLine()) != null) {
                int c = Integer.parseInt(line.substring(4));
                System.out.printf("Edge (%c, %c) with weight %d\n", 
                    line.charAt(0), 
                    line.charAt(2), 
                    c);
            }
            is.close();
        } catch(Exception e) {
            System.err.println("File Error:");
            System.err.println(e);
            return;
        }
    }
}
