/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw3_template;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class hw3Test {
    // Tests here
}
