
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pa2_template;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;

class pa2Test {


    @Test
    public void emptyGraphTest(){
        Graph graph = new Graph();
        Kruskal k = new Kruskal();
        int weight = k.kruskal(graph);
        assertTrue(weight == -1);
    }

    @Test
    public void oneEdgeGraphTest(){
        Graph graph = new Graph();
        Kruskal k = new Kruskal();
        graph.addEdge('A', 'B', 2);
        int weight = k.kruskal(graph);
        assertEquals(weight, 2);
    }
}